<a href="https://colab.research.google.com/github/RafaaelMendonca/bootcamp-avanti/blob/bootcamp/exercicios02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [80]:
import numpy as np
import pandas as pd

def numeros_impares(lista):
  lista_impar = []
  for i in lista:
    if i % 2 != 0:
      lista_impar.append(i)
  return lista_impar

def numeros_primos(lista):
  lista_primos = []
  for i in lista:
    if i > 1:
      for item in range(2,i):
        if item % i == 0:
          break
      else:
        lista_primos.append(i)
  return lista_primos

def listas(lista1, lista2):
  lista_unica = []
  for item in lista1:
    if item not in lista2:
      lista_unica.append(item)

  for item in lista2:
    if item not in lista1:
      lista_unica.append(item)
  return lista_unica

def segundo_maior(lista):
  return sorted(set(lista), reverse=True)[1]

def ordenar_por_nome(lista):
  return sorted(lista, key=lambda pessoa:pessoa[0])

def identificar_tratar_outliers(valor):
  valores = np.array(valor)
  primeiro_quartil = np.percentile(valores, 25)
  terceiro_quartil = np.percentile(valores,75)
  iqr = terceiro_quartil - primeiro_quartil

  limite_inferior = primeiro_quartil - 1.5 * iqr
  limite_superior = terceiro_quartil + 1.5 * iqr
  # Todos os valores que estiverem fora desses limites (superiores e inferiores, são considerados outliers)
  outliers = [x for x in valores if x < limite_inferior or x > limite_superior]
  # para tratar um outlier, primeiramente precisamos analise se faz sentido ou não manter aquele valor... caso não faça sentido:
  valor_tratado = [x for x in valores if limite_inferior <= x <= limite_superior]
  return {
      'outliers' : outliers,
      'tratados' : valor_tratado
  }

def concatenar_dataframes(lista_df, eixo=0):
  return pd.concat(lista_df, axis=eixo, ignore_index=(eixo==0))

def df_csv(arquivo):
  """
  para realizar a leitura de um arquivo CSV basta utilizarmos o .read_csv da bliblioteca pandas,
  para exibir as primeiras linhas utilizamos o .head()
  link dataset: https://www.kaggle.com/datasets/abdulwadood11220/youtube-data-for-analytics-600-rows?resource=download
  """
  df = pd.read_csv(arquivo)
  return df.head()

def filtro(arquivo):
  df = pd.read_csv(arquivo)
  """
  para realizar filtros no DataFrame, podemo utilizar tanto o loc quando o iloc...
  para esse exercicio eu utilizei o .loc para realizar uma condição
  """
  filtro = df.loc[df['comment_count'] > 1000]
  return filtro

def lidar_com_valores_ausentes(arquivo):

  """
  para realizar a ultima atividade sobre valores ausentes, irei utilizar o seguinte dataset:
  https://www.kaggle.com/datasets/brendan45774/test-file
  """

  df = pd.read_csv(arquivo)
  print("valores ausentes: ")
  print(df.isna().sum())
  """
  para modelos de ML, valores ausentes são super prejudiciais, pois podem ocorrer problemas e até mesmo levar falhas nos modelos.
  por isso é bom remover logo de cara ou, caso tenhamos poucos valores, substituir pela média ou mediana (tambem dependendo do tamanho do dataset)

  para esse exemplo eu preferi remover
  """
  df = df.dropna()
  print("\nsem valores ausentes")
  print(df.isna().sum())
  return df

In [4]:
numeros_impares([1,2,3,4,5,6,7,8,9,20])

[1, 3, 5, 7, 9]

In [7]:
numeros_impares([1,2,3,4,5,6,7,8,9,10,11,12,13])

[1, 3, 5, 7, 9, 11, 13]

In [12]:
listas([1,2,3,4,5,6,7,8,9,20], [1,2,3,4,5,6,7,8,9,10,11,12,13])

[20, 10, 11, 12, 13]

In [18]:
segundo_maior([1,2,4,7,8,9,10])

9

In [20]:
pessoas = [
    ("Carlos", 25),
    ("Ana", 30),
    ("Bruno", 22),
    ("Daniela", 28)
]
ordenar_por_nome(pessoas)

[('Ana', 30), ('Bruno', 22), ('Carlos', 25), ('Daniela', 28)]

In [32]:
dados = [10, 12, 13, 15, 14, 16, 18, 90, 95]
resultado = identificar_tratar_outliers(dados)
print(resultado)

{'outliers': [np.int64(90), np.int64(95)], 'tratados': [np.int64(10), np.int64(12), np.int64(13), np.int64(15), np.int64(14), np.int64(16), np.int64(18)]}

In [37]:
df1 = pd.DataFrame({
    'nome': ['Ana', 'Bruno'],
    'idade': [25, 30]
})

df2 = pd.DataFrame({
    'nome': ['Carlos'],
    'cidade': ['Recife']
})
resultado_linhas = concatenar_dataframes([df1, df2], eixo=0)
display(resultado_linhas)

     nome  idade  cidade
0     Ana   25.0     NaN
1   Bruno   30.0     NaN
2  Carlos    NaN  Recife

In [40]:
df_csv('/content/youtube_data.csv')

,video_id,title,description,published_date,channel_id,channel_title,tags,category_id,view_count,like_count,comment_count,duration,thumbnail
0,gsJAlLOFBv0,TINY Tech That Actually Works,No description available,2025-05-02T17:37:10Z,UCMiJRAwDNSNzuYeN2uWa0pA,Mrwhosetheboss,"['tiny', 'tech', 'gadgets', 'small', 'miniature']",28,8962092.0,243350.0,515.0,PT57S,https://i.ytimg.com/vi/gsJAlLOFBv0/default.jpg
1,ypicIkaiViM,AI & future of workforce: Andrew Yang on how t...,"Andrew Yang, Forward Party co-chair and former...",2025-06-18T12:39:53Z,UCrp_UI8XtuYfpiqluWLD7Lw,CNBC Television,"['Squawk Box U.S.', 'CNBC', 'business news', '...",25,289626.0,3393.0,1240.0,PT7M50S,https://i.ytimg.com/vi/ypicIkaiViM/default.jpg
2,1Nef8LPO-jo,5 ILLEGAL gadgets that will get you ARRESTED,#shorts #technology \n\nI spend a LOT of time ...,2022-11-01T11:00:06Z,UCMiJRAwDNSNzuYeN2uWa0pA,Mrwhosetheboss,"['shorts', 'tech']",28,81372201.0,4178447.0,6378.0,PT47S,https://i.ytimg.com/vi/1Nef8LPO-jo/default.jpg
3,lCHqmzynO-s,Overrated vs. Underrated Tech,💬 Join my Discord server: https://discord.gg/g...,2024-07-08T18:04:31Z,UCPk2s5c4R_d-EUUNvFFODoA,Gohar Khan,"['thailand', 'surin', 'style', 'travel', 'day'...",27,21255964.0,909386.0,2681.0,PT31S,https://i.ytimg.com/vi/lCHqmzynO-s/default.jpg
4,7uFrtqSwYzM,APPLE Glass Revolutionizes AR Experience Forever!,Discover the revolutionary world of augmented ...,2024-12-22T16:49:00Z,UCxqG_E-68WAE0TWYfIopv6Q,Digifix,"['apple glasses price', 'apple glasses design'...",28,2790436.0,44278.0,1359.0,PT16S,https://i.ytimg.com/vi/7uFrtqSwYzM/default.jpg

In [41]:
df = pd.read_csv('/content/youtube_data.csv')

In [53]:
filtro('/content/youtube_data.csv')

,video_id,title,description,published_date,channel_id,channel_title,tags,category_id,view_count,like_count,comment_count,duration,thumbnail
1,ypicIkaiViM,AI & future of workforce: Andrew Yang on how t...,"Andrew Yang, Forward Party co-chair and former...",2025-06-18T12:39:53Z,UCrp_UI8XtuYfpiqluWLD7Lw,CNBC Television,"['Squawk Box U.S.', 'CNBC', 'business news', '...",25,289626.0,3393.0,1240.0,PT7M50S,https://i.ytimg.com/vi/ypicIkaiViM/default.jpg
2,1Nef8LPO-jo,5 ILLEGAL gadgets that will get you ARRESTED,#shorts #technology \n\nI spend a LOT of time ...,2022-11-01T11:00:06Z,UCMiJRAwDNSNzuYeN2uWa0pA,Mrwhosetheboss,"['shorts', 'tech']",28,81372201.0,4178447.0,6378.0,PT47S,https://i.ytimg.com/vi/1Nef8LPO-jo/default.jpg
3,lCHqmzynO-s,Overrated vs. Underrated Tech,💬 Join my Discord server: https://discord.gg/g...,2024-07-08T18:04:31Z,UCPk2s5c4R_d-EUUNvFFODoA,Gohar Khan,"['thailand', 'surin', 'style', 'travel', 'day'...",27,21255964.0,909386.0,2681.0,PT31S,https://i.ytimg.com/vi/lCHqmzynO-s/default.jpg
4,7uFrtqSwYzM,APPLE Glass Revolutionizes AR Experience Forever!,Discover the revolutionary world of augmented ...,2024-12-22T16:49:00Z,UCxqG_E-68WAE0TWYfIopv6Q,Digifix,"['apple glasses price', 'apple glasses design'...",28,2790436.0,44278.0,1359.0,PT16S,https://i.ytimg.com/vi/7uFrtqSwYzM/default.jpg
5,THw-wXt7wyM,5 Tech Myths Busted!,#shorts \n\nI spend a LOT of time trying to ma...,2022-10-02T19:40:14Z,UCMiJRAwDNSNzuYeN2uWa0pA,Mrwhosetheboss,"['shorts', 'tech', 'myths', 'busted', 'tips']",28,28131104.0,1956461.0,6253.0,PT56S,https://i.ytimg.com/vi/THw-wXt7wyM/default.jpg
...,...,...,...,...,...,...,...,...,...,...,...,...,...
586,6KUd0csOsXY,This New Upcoming Phone - Will Be the King of ...,New upcoming phone april month ka....\n\n#Upco...,2025-03-25T14:39:27Z,UC1tVU8H153ZFO9eRsxdJlhA,Technology Gyan,"['New Phone', 'New Upcoming Phone', 'April', '...",28,1121422.0,50297.0,3630.0,PT9M51S,https://i.ytimg.com/vi/6KUd0csOsXY/default.jpg
587,xBpN_Mm-YLc,Samsung Galaxy M56 Unboxing & First Look⚡Slimm...,Doston aaj ke video me hum unbox kar rahe hain...,2025-04-18T11:45:21Z,UCEPL07qzVsOcHd3sMUws65g,Trakin Tech,"['samsung galaxy m56', 'samsung galaxy m56 pri...",28,1035950.0,30510.0,1719.0,PT9M38S,https://i.ytimg.com/vi/xBpN_Mm-YLc/default.jpg
589,sfe8Clx2h5Q,TrakinTech Presents India's Biggest Tech Round...,"Doston ye hain 2024 ka sabse bada video, jisme...",2024-12-23T06:30:06Z,UCEPL07qzVsOcHd3sMUws65g,Trakin Tech,"['TrakinTech', 'Trakin Tech', ""india's biggest...",28,2767552.0,100306.0,10287.0,PT2H49M43S,https://i.ytimg.com/vi/sfe8Clx2h5Q/default.jpg
594,kLf6c8BerhE,I Played GTA 6 Before Launch ! *Exclusive*,gta kheli li jae\n\n🔥 Subscribe for Tabahi Vid...,2025-04-01T18:28:31Z,UCXUJJNoP1QupwsYIWFXmsZg,Tech Burner,"['gta 6', 'gta 6 trailer', 'gta 6 news', 'gta ...",28,2602266.0,105714.0,5071.0,PT12M44S,https://i.ytimg.com/vi/kLf6c8BerhE/default.jpg
595,jWiV4bWsDl4,Puse a prueba estos rayos x para ver a traves ...,Canal principal: https://www.youtube.com/c/Pon...,2022-05-03T22:23:10Z,UCPx9eXszFK8rkivV7tXZpHA,PONGAMOSLO A PRUEBA CORTOS,"['walabot', 'ver tubos en las paredes', 'ver m...",24,15631786.0,1692338.0,4662.0,PT1M,https://i.ytimg.com/vi/jWiV4bWsDl4/default.jpg

In [81]:
lidar_com_valores_ausentes('/content/tested.csv')

valores ausentes:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

sem valores ausentes
PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
12,904,1,1,"Snyder, Mrs. John Pillsbury (Nelle Stevenson)",female,23.0,1,0,21228,82.2667,B45,S
14,906,1,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance...",female,47.0,1,0,W.E.P. 5734,61.1750,E31,S
24,916,1,1,"Ryerson, Mrs. Arthur Larned (Emily Maria Borie)",female,48.0,1,3,PC 17608,262.3750,B57 B59 B63 B66,C
26,918,1,1,"Ostby, Miss. Helene Ragnhild",female,22.0,0,1,113509,61.9792,B36,C
28,920,0,1,"Brady, Mr. John Bertram",male,41.0,0,0,113054,30.5000,A21,S
...,...,...,...,...,...,...,...,...,...,...,...,...
404,1296,0,1,"Frauenthal, Mr. Isaac Gerald",male,43.0,1,0,17765,27.7208,D40,C
405,1297,0,2,"Nourney, Mr. Alfred (Baron von Drachstedt"")""",male,20.0,0,0,SC/PARIS 2166,13.8625,D38,C
407,1299,0,1,"Widener, Mr. George Dunton",male,50.0,1,1,113503,211.5000,C80,C
411,1303,1,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.0,1,0,19928,90.0000,C78,Q
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C